# Generated by Django 3.1.4 on 2021-02-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Maritialstatus', models.CharField(default='', max_length=100)),
                ('Educationalqualification', models.CharField(default='', max_length=100)),
                ('Languageknown', models.CharField(choices=[('malayalam', 'Malayalam'), ('english', 'English'), ('hindi', 'Hindi')], max_length=100)),
                ('Password', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
                ('Photo', models.ImageField(upload_to='media/')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
