# Generated by Django 3.1.4 on 2021-02-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='District',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
