# Generated by Django 3.1.4 on 2021-02-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0004_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='Colour',
            new_name='Entryticket',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='Price',
            new_name='Entrytime',
        ),
    ]
