# Generated by Django 3.1.4 on 2021-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0005_auto_20210217_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='Entryticket',
            new_name='Colour',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='Entrytime',
            new_name='Price',
        ),
    ]
